# Generated by Django 5.0.8 on 2024-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_date_updated_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='default_images/banner.jpg', upload_to='banners/'),
        ),
    ]
