# Generated by Django 5.0.8 on 2024-08-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
